/**
 * export-spec.test.js — the exported report must describe what is on screen.
 * Run: node export-spec.test.js → "ALL TESTS PASSED (N assertions)".
 *
 * The report was once generated by POST /api/reports/generate with reportType
 * 'full', and that endpoint took no date range at all — it rendered its own
 * default window. The user's month selection and comparison were discarded on
 * the way out, so the downloaded file showed six months no matter what had
 * been chosen, with nothing warning about the substitution.
 *
 * buildExportSpec is the pure description of the current view, and the report
 * is rendered from it. Both are pinned here.
 */
'use strict';

// dashboard.js registers a DOMContentLoaded handler and reads the DOM for the
// insights section; enough of a stub to let it load and render under Node.
global.document = { querySelectorAll: () => [], addEventListener: () => {} };

const { buildExportSpec, percentDelta, buildReportHtml } = require('./dashboard.js');

let n = 0;
function assert(cond, msg) {
  n++;
  if (!cond) { throw new Error('FAILED #' + n + ': ' + msg); }
}
function eq(a, b, msg) {
  assert(a === b, (msg || '') + ' (got ' + JSON.stringify(a) + ', expected ' + JSON.stringify(b) + ')');
}
function deepEqArr(a, b, msg) {
  eq(JSON.stringify(a), JSON.stringify(b), msg);
}

/** The dashboard state, defaulting to a single selected month, no comparison. */
const view = (over) => Object.assign({
  businessId: 'biz-1',
  startYear: 2026, startMonth: 3,
  endYear: 2026, endMonth: 3,
  metricType: 'overview',
  compareEnabled: false,
  compareMode: 'yoy',
  compareYear: null, compareMonth: null,
}, over);

// ── The spec: what the user is looking at ────────────────────────────────

// 1. The selected range is carried through exactly, not widened to six months.
{
  const s = buildExportSpec(view({ startYear: 2026, startMonth: 1, endYear: 2026, endMonth: 3 }));
  eq(s.startMonth, 1, 'start month is the selected one');
  eq(s.endMonth, 3, 'end month is the selected one');
  eq(s.monthsCount, 3, 'three months selected means three months exported');
  eq(s.periodLabel, 'January 2026 – March 2026', 'label names the real range');
}

// 2. A single month reads as one month, not as a range of one.
{
  const s = buildExportSpec(view({ startMonth: 7, endMonth: 7 }));
  eq(s.monthsCount, 1, 'one month');
  eq(s.periodLabel, 'July 2026', 'a single month is not written as "July – July"');
}

// 3. A range spanning a year boundary counts correctly.
{
  const s = buildExportSpec(view({ startYear: 2025, startMonth: 11, endYear: 2026, endMonth: 2 }));
  eq(s.monthsCount, 4, 'Nov, Dec, Jan, Feb');
  eq(s.periodLabel, 'November 2025 – February 2026', 'and spans the year in the label');
}

// 4. The baseline is named in full, not just by its kind. "YoY" tells a reader
//    what sort of comparison it is; only the months tell them what it covers.
{
  const s = buildExportSpec(view({
    startYear: 2026, startMonth: 1, endYear: 2026, endMonth: 3,
    compareEnabled: true, compareMode: 'yoy',
  }));
  eq(s.compareLabel, 'YoY', 'the kind of comparison');
  eq(s.comparePeriodLabel, 'January 2025 – March 2025', 'and the months it actually covers');
}

// 5. Previous period: the block immediately before the selection, same length.
{
  const s = buildExportSpec(view({
    startYear: 2026, startMonth: 4, endYear: 2026, endMonth: 6,
    compareEnabled: true, compareMode: 'prev',
  }));
  eq(s.compareLabel, 'PoP', 'previous period');
  eq(s.comparePeriodLabel, 'January 2026 – March 2026',
     'the three months immediately before the selection, never overlapping it');
}

// 6. Previous period across a year boundary.
{
  const s = buildExportSpec(view({
    startYear: 2026, startMonth: 1, endYear: 2026, endMonth: 2,
    compareEnabled: true, compareMode: 'prev',
  }));
  eq(s.comparePeriodLabel, 'November 2025 – December 2025', 'wraps back into the previous year');
}

// 7. Custom mode names the one month the user picked.
{
  const s = buildExportSpec(view({
    compareEnabled: true, compareMode: 'custom',
    compareYear: 2024, compareMonth: 12,
  }));
  eq(s.comparePeriodLabel, 'December 2024', 'named by that month alone');
}

// 8. Custom mode with nothing chosen yet must not invent a baseline, and must
//    not claim the API can reproduce a view that is not fully specified.
{
  const s = buildExportSpec(view({
    compareEnabled: true, compareMode: 'custom',
    compareYear: null, compareMonth: null,
  }));
  eq(s.comparePeriodLabel, null, 'an incomplete custom selection names no baseline');
  eq(s.canUseApi, false, 'and the API path is refused rather than guessed at');
}

// 9. percentDelta — the report prints these next to every metric.
{
  eq(percentDelta(150, 100), 50, 'a rise');
  eq(percentDelta(50, 100), -50, 'a fall');
  eq(percentDelta(100, 100), 0, 'flat');
  eq(percentDelta(0, 100), -100, 'down to nothing is a real -100%, not a null');
  // Dividing by a zero baseline is undefined, not "infinite growth". The report
  // prints "no baseline" for this instead of a fabricated percentage.
  eq(percentDelta(500, 0), null, 'no baseline gives null, never Infinity');
  eq(percentDelta(0, 0), null, 'nothing against nothing is still no baseline');
}

// ── The rendered report ──────────────────────────────────────────────────

const MT = ['overview', 'calls', 'website_clicks', 'directions', 'bookings', 'chat_clicks'];

// Distinct series per metric type, so a test can tell which one actually got
// charted rather than merely noticing that a chart was drawn.
const SERIES = {
  overview: [200, 300, 400],
  calls: [11, 22, 33],
  directions: [55, 66, 77],
};

function render(over) {
  const metricsData = {}, totals = {}, compareTotals = {};
  for (const mt of MT) {
    const vals = SERIES[mt] || [200, 300, 400];
    metricsData[mt] = vals.map((total, i) => ({ year: 2026, month: i + 1, total }));
    totals[mt] = vals.reduce((a, b) => a + b, 0);
    compareTotals[mt] = { cur: totals[mt], base: 600 };
  }
  return buildReportHtml(Object.assign({
    bizName: 'Acme Ltd',
    periodLabel: 'January 2026 – March 2026',
    startLabel: 'January 2026', endLabel: 'March 2026',
    allMonthsCount: 3,
    totals, metricsData,
    latestBreakdown: null, latestSearchTerms: null, latestFunnel: null,
    overviewCompare: [100, null, 200],
    compareLabel: 'YoY',
    compareTotals,
    comparePeriodLabel: 'January 2025 – March 2025',
  }, over));
}

// 10. Both periods are named, and every card carries its own change.
{
  const html = render();
  assert(html.includes('January 2026 – March 2026'), 'the selected period is named');
  assert(html.includes('January 2025 – March 2025'), 'so is the baseline');
  assert(/class="report-vs"/.test(html), 'the header states what it is compared against');
  assert(/class="metric-delta metric-delta-up"/.test(html), '900 against 600 is a rise');
  assert(/50\.0%/.test(html), 'reported as +50%');
  assert(/vs 600/.test(html), 'and shows the baseline figure it was measured from');
}

// 11. A month the baseline never covered says so. Printing nothing there made
//     an uncollected month look identical to one that simply did not change.
{
  const html = render();
  const tags = (html.match(/YoY [^<]*/g) || []);
  eq(tags.length, 3, 'one label per month');
  eq(tags[0], 'YoY +100.0%', 'Jan: 200 against 100');
  eq(tags[1], 'YoY pending', 'Feb was never collected and admits it');
  eq(tags[2], 'YoY +100.0%', 'Mar: 400 against 200');
}

// 12. The baseline is drawn as a dashed second line, lifting over the gap
//     rather than plotting it as zero — which would draw a collapse to the
//     axis that never happened.
{
  const html = render();
  const dashed = (html.match(/stroke-dasharray="6 4"/g) || []);
  eq(dashed.length, 1, 'one baseline line');
  assert(!/,NaN/.test(html), 'and no NaN coordinates from the missing month');
  assert(/class="chart-legend"/.test(html), 'with a legend naming both lines');
}

// 13. A zero baseline prints "no baseline" rather than a fabricated percentage.
{
  const compareTotals = {};
  for (const mt of MT) compareTotals[mt] = { cur: 900, base: 0 };
  const html = render({ compareTotals });
  assert(/no baseline/.test(html), 'a zero baseline is stated, never divided by');
  assert(!/Infinity/.test(html), 'and never leaks an Infinity into the report');
}

// 14. With no comparison data at all the report still renders — it simply
//     makes no claims about change.
{
  const html = render({ overviewCompare: null, compareTotals: {}, comparePeriodLabel: null });
  assert(html.includes('January 2026 – March 2026'), 'the period is still named');
  assert(!/class="report-vs"/.test(html), 'but nothing claims a comparison');
  assert(!/class="chart-legend"/.test(html), 'and no legend for a line that is not drawn');
  // Matched on the markup: the class names also appear in the report's inline
  // stylesheet whether or not any delta is rendered.
  assert(!/class="metric-delta/.test(html), 'and no deltas on the cards');
}

// 15. buildExportSpec carries the active tab through as focusMetricType, so a
//     report built while looking at Calls says so, not just Overview.
{
  const s1 = buildExportSpec(view({ metricType: 'overview' }));
  eq(s1.focusMetricType, 'overview', 'defaults to overview');
  const s2 = buildExportSpec(view({ metricType: 'calls' }));
  eq(s2.focusMetricType, 'calls', 'carries whichever tab is active');
}

// 16. The trend chart is built from the metric that was on screen, not always
//     'overview'. This is the actual bug report: switching to Calls or
//     Directions and exporting still produced an Overview chart, with nothing
//     in the file to say the metric had been silently substituted.
{
  // The point-value labels drawn by buildReportChartSvg have a distinctive
  // shape, so this looks only at what the CHART plots, not at the monthly
  // breakdown table further down the page, which correctly still lists every
  // metric type's raw numbers regardless of which one is charted.
  const chartValues = (html) => (html.match(/font-weight="600">([\d,]+)<\/text>/g) || [])
    .map(m => m.match(/>([\d,]+)</)[1]);

  const overviewHtml   = render({ focusMetricType: 'overview' });
  const callsHtml      = render({ focusMetricType: 'calls' });
  const directionsHtml = render({ focusMetricType: 'directions' });

  deepEqArr(chartValues(overviewHtml), ['200', '300', '400'], 'overview chart plots the overview series');
  deepEqArr(chartValues(callsHtml), ['11', '22', '33'], 'switching to Calls charts the calls series, not what was there before');
  assert(/Phone Calls Trend/.test(callsHtml), 'and the heading names the metric being charted');

  deepEqArr(chartValues(directionsHtml), ['55', '66', '77'], 'Directions charts its own series');
  assert(/Directions Trend/.test(directionsHtml), 'with its own heading');
}

// 17. An unrecognised or missing focus falls back to overview rather than
//     rendering a blank chart — a report must always show something.
{
  const html = render({ focusMetricType: 'nonexistent_metric' });
  assert(/>200<|>300<|>400</.test(html), 'an unknown metric type falls back to overview');
}

console.log(`ALL TESTS PASSED (${n} assertions)`);
